services:
  # NATS with JetStream enabled
  nats:
    image: nats:latest
    container_name: nats-jetstream
    command: "-js -m 8222"
    ports:
      - "4222:4222"
      - "8222:8222"

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-gomemory
    ports:
      - "6336:6334" # gRPC port
      - "6335:6333" # HTTP port

  # PostgreSQL
  postgres:
    image: postgres:latest
    container_name: gomemory
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: memory
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Python Embedding Microservice
  embedding:
    image: prateek329/embedding-service
    container_name: embedding-microservice
    ports:
      - "50051:50051"

  # Redis (Added)
  redis:
    image: redis:latest
    container_name: Go_Memory_Redis
    # This enables the AOF persistence we discussed
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data: # Crucial: This defines the volume for Redis