global:
  scrape_interval: 5s # Scrape often for testing

scrape_configs:
  # Job 1: Prometheus monitoring itself (Keep this)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Job 2: YOUR GO MEMORY APP (The Fix)
  - job_name: 'go-memory-app'
    metrics_path: '/metrics'
    static_configs:
      # host.docker.internal points to your WSL/Windows host machine
      # REPLACE '8080' WITH YOUR ACTUAL GO SERVER PORT
      - targets: ['172.21.97.207:9000']